
package com.raja.studentservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StudentOpearationsImplService", targetNamespace = "http://studentservice.raja.com/", wsdlLocation = "http://localhost:5000/student/get/details?wsdl")
public class StudentOpearationsImplService
    extends Service
{

    private final static URL STUDENTOPEARATIONSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException STUDENTOPEARATIONSIMPLSERVICE_EXCEPTION;
    private final static QName STUDENTOPEARATIONSIMPLSERVICE_QNAME = new QName("http://studentservice.raja.com/", "StudentOpearationsImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:5000/student/get/details?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STUDENTOPEARATIONSIMPLSERVICE_WSDL_LOCATION = url;
        STUDENTOPEARATIONSIMPLSERVICE_EXCEPTION = e;
    }

    public StudentOpearationsImplService() {
        super(__getWsdlLocation(), STUDENTOPEARATIONSIMPLSERVICE_QNAME);
    }

    public StudentOpearationsImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), STUDENTOPEARATIONSIMPLSERVICE_QNAME, features);
    }

    public StudentOpearationsImplService(URL wsdlLocation) {
        super(wsdlLocation, STUDENTOPEARATIONSIMPLSERVICE_QNAME);
    }

    public StudentOpearationsImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STUDENTOPEARATIONSIMPLSERVICE_QNAME, features);
    }

    public StudentOpearationsImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StudentOpearationsImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StudentOpearationsImpl
     */
    @WebEndpoint(name = "StudentOpearationsImplPort")
    public StudentOpearationsImpl getStudentOpearationsImplPort() {
        return super.getPort(new QName("http://studentservice.raja.com/", "StudentOpearationsImplPort"), StudentOpearationsImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StudentOpearationsImpl
     */
    @WebEndpoint(name = "StudentOpearationsImplPort")
    public StudentOpearationsImpl getStudentOpearationsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://studentservice.raja.com/", "StudentOpearationsImplPort"), StudentOpearationsImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STUDENTOPEARATIONSIMPLSERVICE_EXCEPTION!= null) {
            throw STUDENTOPEARATIONSIMPLSERVICE_EXCEPTION;
        }
        return STUDENTOPEARATIONSIMPLSERVICE_WSDL_LOCATION;
    }

}
