
package com.raja.studentservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StudentOpearationsImpl", targetNamespace = "http://studentservice.raja.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StudentOpearationsImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.raja.studentservice.Student
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStudentById", targetNamespace = "http://studentservice.raja.com/", className = "com.raja.studentservice.GetStudentById")
    @ResponseWrapper(localName = "getStudentByIdResponse", targetNamespace = "http://studentservice.raja.com/", className = "com.raja.studentservice.GetStudentByIdResponse")
    @Action(input = "http://studentservice.raja.com/StudentOpearationsImpl/getStudentByIdRequest", output = "http://studentservice.raja.com/StudentOpearationsImpl/getStudentByIdResponse")
    public Student getStudentById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStudentNameById", targetNamespace = "http://studentservice.raja.com/", className = "com.raja.studentservice.GetStudentNameById")
    @ResponseWrapper(localName = "getStudentNameByIdResponse", targetNamespace = "http://studentservice.raja.com/", className = "com.raja.studentservice.GetStudentNameByIdResponse")
    @Action(input = "http://studentservice.raja.com/StudentOpearationsImpl/getStudentNameByIdRequest", output = "http://studentservice.raja.com/StudentOpearationsImpl/getStudentNameByIdResponse")
    public String getStudentNameById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
